/* ===== Star Party — beginner showpiece catalog =====
   A curated pool of bright, easy targets for a public star party with a
   beginner telescope. The "Tonight" feature picks which of these are actually
   above the horizon for a chosen location/date and ranks them.

   kind 'planet'  -> position computed live from `body` (Astronomy.Body name)
   kind 'fixed'   -> fixed sky position from ra (decimal hours) / dec (degrees), J2000
   showpiece      -> 1..5 "wow" weight for a general crowd
   moonSensitive  -> true for faint objects a bright Moon washes out
*/
window.SP_CATALOG = [
  // ---------- Solar system (computed live) ----------
  { id:'moon', name:'The Moon', kind:'planet', body:'Moon', type:'Moon', constellation:'', showpiece:5, moonSensitive:false,
    look:'Cruise along the terminator (the day/night line) — that’s where crater shadows are sharpest.',
    facts:'Our only natural satellite, ~239,000 miles away. Those dark patches are ancient lava plains called "maria" (seas).' },
  { id:'venus', name:'Venus', kind:'planet', body:'Venus', type:'Planet', constellation:'', showpiece:4, moonSensitive:false,
    look:'Look for its phase — like a tiny moon. It’s blindingly bright; best caught in twilight.',
    facts:'The hottest planet (~870°F) under a runaway greenhouse atmosphere. Brightest object after the Sun and Moon.' },
  { id:'jupiter', name:'Jupiter', kind:'planet', body:'Jupiter', type:'Planet', constellation:'', showpiece:5, moonSensitive:false,
    look:'Spot the 4 bright Galilean moons in a line, plus the two dark cloud belts across the disk.',
    facts:'The largest planet — over 1,300 Earths would fit inside. Galileo’s moons (1610) proved not everything orbits Earth.' },
  { id:'saturn', name:'Saturn', kind:'planet', body:'Saturn', type:'Planet', constellation:'', showpiece:5, moonSensitive:false,
    look:'The rings! Even a small scope shows them. The big moon Titan sits nearby as a star-like dot.',
    facts:'The rings are mostly water ice, from dust grains to house-sized chunks, yet only ~30 ft thick on average.' },
  { id:'mars', name:'Mars', kind:'planet', body:'Mars', type:'Planet', constellation:'', showpiece:4, moonSensitive:false,
    look:'A small orange dot; near opposition you may glimpse a white polar cap or dark markings.',
    facts:'The Red Planet — rusty iron dust gives its color. Home to the tallest volcano in the solar system, Olympus Mons.' },
  { id:'mercury', name:'Mercury', kind:'planet', body:'Mercury', type:'Planet', constellation:'', showpiece:2, moonSensitive:false,
    look:'Very low near the horizon in bright twilight — needs a clear, flat view. Shows a phase.',
    facts:'The smallest planet and closest to the Sun, never straying far from it in our sky.' },

  // ---------- Globular clusters (bright; survive moonlight) ----------
  { id:'m13', name:'M13 – Hercules Cluster', kind:'fixed', ra:16.6949, dec:36.4613, type:'Globular cluster', constellation:'Hercules', mag:5.8, showpiece:5, moonSensitive:false,
    look:'A fuzzy ball that resolves into a swarm of stars with a bit of magnification.',
    facts:'Several hundred thousand stars packed into a ball ~145 light-years across, orbiting our galaxy. ~25,000 ly away.' },
  { id:'m22', name:'M22 – Sagittarius Cluster', kind:'fixed', ra:18.6065, dec:-23.9033, type:'Globular cluster', constellation:'Sagittarius', mag:5.1, showpiece:4, moonSensitive:false,
    look:'One of the brightest globulars — a big grainy ball of stars. Sits low in the south.',
    facts:'Closer than most globulars (~10,000 ly) and easily seen with binoculars; one of the first ever discovered.' },
  { id:'m4', name:'M4 – Cat’s Eye Cluster', kind:'fixed', ra:16.3933, dec:-26.5258, type:'Globular cluster', constellation:'Scorpius', mag:5.6, showpiece:3, moonSensitive:false,
    look:'A loose globular right next to bright red Antares — easy to find.',
    facts:'One of the nearest globular clusters (~7,200 ly). A central bar of stars runs across its core.' },
  { id:'m92', name:'M92 – Globular in Hercules', kind:'fixed', ra:17.2851, dec:43.1361, type:'Globular cluster', constellation:'Hercules', mag:6.4, showpiece:3, moonSensitive:false,
    look:'A tight, bright globular — M13’s often-overlooked neighbor.',
    facts:'About 27,000 light-years away and roughly 14 billion years old — nearly as old as the universe.' },

  // ---------- Open star clusters ----------
  { id:'m11', name:'M11 – Wild Duck Cluster', kind:'fixed', ra:18.8511, dec:-6.2700, type:'Open cluster', constellation:'Scutum', mag:5.8, showpiece:4, moonSensitive:false,
    look:'A dense, sparkling fan of stars — the brightest stars form a "V" like a flight of ducks.',
    facts:'One of the richest open clusters — about 2,900 stars, ~6,200 light-years away.' },
  { id:'m45', name:'M45 – Pleiades', kind:'fixed', ra:3.7833, dec:24.1167, type:'Open cluster', constellation:'Taurus', mag:1.6, showpiece:5, moonSensitive:false,
    look:'Best at low power or in binoculars — a tiny dipper of brilliant blue-white stars.',
    facts:'The "Seven Sisters," ~440 ly away. Young hot stars only ~100 million years old, drifting through a dust cloud.' },
  { id:'m44', name:'M44 – Beehive Cluster', kind:'fixed', ra:8.6700, dec:19.6833, type:'Open cluster', constellation:'Cancer', mag:3.7, showpiece:4, moonSensitive:false,
    look:'A big, loose scatter of stars — use low power so the whole swarm fits.',
    facts:'Known since ancient times as a misty patch; Galileo first resolved it into ~1,000 stars.' },
  { id:'doublecluster', name:'The Double Cluster', kind:'fixed', ra:2.3333, dec:57.1333, type:'Open cluster', constellation:'Perseus', mag:4.3, showpiece:4, moonSensitive:false,
    look:'Two glittering star clusters side by side in one low-power view — a showstopper.',
    facts:'A pair of young clusters (~7,500 ly) only a few million years old, packed with hot supergiant stars.' },
  { id:'m6', name:'M6 – Butterfly Cluster', kind:'fixed', ra:17.6711, dec:-32.2417, type:'Open cluster', constellation:'Scorpius', mag:4.2, showpiece:3, moonSensitive:false,
    look:'A bright cluster whose stars outline butterfly wings. Low in the south.',
    facts:'About 1,600 light-years away; its brightest star is an orange variable.' },
  { id:'m7', name:'M7 – Ptolemy Cluster', kind:'fixed', ra:17.8967, dec:-34.7931, type:'Open cluster', constellation:'Scorpius', mag:3.3, showpiece:3, moonSensitive:false,
    look:'A large, bright scatter of stars near the Scorpion’s stinger. Best in binoculars.',
    facts:'Recorded by Ptolemy in 130 AD. Close by at ~980 ly and a comfortable naked-eye glow under dark skies.' },

  // ---------- Double & colorful stars (immune to moonlight) ----------
  { id:'albireo', name:'Albireo', kind:'fixed', ra:19.5121, dec:27.9597, type:'Double star', constellation:'Cygnus', mag:3.1, showpiece:5, moonSensitive:false,
    look:'Split it at medium power — a gorgeous gold star paired with a smaller blue one.',
    facts:'The "head" of the Swan and the sky’s most beautiful color-contrast double. ~430 light-years away.' },
  { id:'mizar', name:'Mizar & Alcor', kind:'fixed', ra:13.3988, dec:54.9254, type:'Double star', constellation:'Ursa Major', mag:2.2, showpiece:4, moonSensitive:false,
    look:'The bend in the Big Dipper’s handle — two stars to the eye, and Mizar itself splits in the scope.',
    facts:'A classic "test" double. Mizar was the first double star ever photographed (1857).' },
  { id:'doubledouble', name:'The Double-Double (Epsilon Lyrae)', kind:'fixed', ra:18.7383, dec:39.6703, type:'Double star', constellation:'Lyra', mag:4.7, showpiece:4, moonSensitive:false,
    look:'Near Vega. Looks like two stars — crank up the power and each splits into two again.',
    facts:'A true quadruple star system, all gravitationally bound, about 160 light-years away.' },
  { id:'antares', name:'Antares', kind:'fixed', ra:16.4901, dec:-26.4319, type:'Star (red supergiant)', constellation:'Scorpius', mag:1.0, showpiece:3, moonSensitive:false,
    look:'A distinctly orange-red star — the "heart of the Scorpion," low in the south.',
    facts:'A red supergiant ~700x the Sun’s diameter. Its name means "rival of Mars" for its similar ruddy color.' },
  { id:'arcturus', name:'Arcturus', kind:'fixed', ra:14.2610, dec:19.1825, type:'Star (orange giant)', constellation:'Boötes', mag:0.0, showpiece:3, moonSensitive:false,
    look:'A brilliant warm-orange star high overhead — "arc to Arcturus" off the Dipper’s handle.',
    facts:'The brightest star in the northern sky, ~37 ly away, racing through the galaxy at an unusual angle.' },
  { id:'vega', name:'Vega', kind:'fixed', ra:18.6156, dec:38.7837, type:'Star (blue-white)', constellation:'Lyra', mag:0.0, showpiece:3, moonSensitive:false,
    look:'A dazzling blue-white beacon nearly overhead in summer — a corner of the Summer Triangle.',
    facts:'Only 25 ly away; it was the northern pole star ~12,000 years ago and will be again in ~13,000 years.' },
  { id:'polaris', name:'Polaris (North Star)', kind:'fixed', ra:2.5303, dec:89.2641, type:'Double star', constellation:'Ursa Minor', mag:2.0, showpiece:3, moonSensitive:false,
    look:'The sky pivots around it. A scope reveals a faint companion star beside it.',
    facts:'Sits almost exactly above Earth’s North Pole, so it barely moves all night — the sailor’s anchor star.' },
  { id:'betelgeuse', name:'Betelgeuse', kind:'fixed', ra:5.9195, dec:7.4071, type:'Star (red supergiant)', constellation:'Orion', mag:0.5, showpiece:3, moonSensitive:false,
    look:'Orion’s orange-red shoulder — obvious color contrast with blue-white Rigel.',
    facts:'A red supergiant so huge it would swallow Jupiter’s orbit. It will explode as a supernova — someday.' },
  { id:'rigel', name:'Rigel', kind:'fixed', ra:5.2423, dec:-8.2017, type:'Star (blue supergiant)', constellation:'Orion', mag:0.1, showpiece:3, moonSensitive:false,
    look:'Orion’s brilliant blue-white foot. A small faint companion hides in the glare.',
    facts:'A blue supergiant ~120,000x more luminous than the Sun, about 860 light-years away.' },
  { id:'sirius', name:'Sirius', kind:'fixed', ra:6.7525, dec:-16.7161, type:'Star (brightest)', constellation:'Canis Major', mag:-1.4, showpiece:4, moonSensitive:false,
    look:'The brightest star in the night sky — watch it flash colors when low ("the Dog Star twinkling").',
    facts:'Just 8.6 ly away. Has a tiny white-dwarf companion, "the Pup," the dense cinder of a dead star.' },
  { id:'capella', name:'Capella', kind:'fixed', ra:5.2782, dec:45.9980, type:'Star (yellow giant)', constellation:'Auriga', mag:0.1, showpiece:2, moonSensitive:false,
    look:'A bright golden star high in winter — actually a close pair of giant suns.',
    facts:'The 6th-brightest star, ~43 ly away; two yellow giant stars orbiting each other.' },
  { id:'aldebaran', name:'Aldebaran', kind:'fixed', ra:4.5987, dec:16.5093, type:'Star (orange giant)', constellation:'Taurus', mag:0.9, showpiece:2, moonSensitive:false,
    look:'The fiery orange "eye" of Taurus the Bull, near the Pleiades.',
    facts:'An orange giant ~65 ly away; it only appears to sit in the Hyades cluster but is much closer to us.' },

  // ---------- Nebulae & galaxy (faint; Moon-sensitive) ----------
  { id:'m42', name:'M42 – Orion Nebula', kind:'fixed', ra:5.5881, dec:-5.3911, type:'Nebula', constellation:'Orion', mag:4.0, showpiece:5, moonSensitive:true,
    look:'A glowing wing of gray-green gas wrapped around the 4 "Trapezium" stars at its heart.',
    facts:'A vast stellar nursery ~1,340 ly away where new stars are being born right now. The best nebula for beginners.' },
  { id:'m57', name:'M57 – Ring Nebula', kind:'fixed', ra:18.8933, dec:33.0297, type:'Nebula (planetary)', constellation:'Lyra', mag:8.8, showpiece:4, moonSensitive:false,
    look:'A tiny gray smoke-ring between two stars of Lyra — use medium-to-high power.',
    facts:'A dying Sun-like star that puffed off its outer layers; we see the glowing shell ~2,500 ly away.' },
  { id:'m27', name:'M27 – Dumbbell Nebula', kind:'fixed', ra:19.9936, dec:22.7211, type:'Nebula (planetary)', constellation:'Vulpecula', mag:7.4, showpiece:4, moonSensitive:true,
    look:'A bright apple-core / hourglass glow — one of the easiest planetary nebulae.',
    facts:'Another Sun-like star at the end of its life, ~1,360 ly away; the first planetary nebula ever discovered.' },
  { id:'m8', name:'M8 – Lagoon Nebula', kind:'fixed', ra:18.0606, dec:-24.3867, type:'Nebula', constellation:'Sagittarius', mag:6.0, showpiece:4, moonSensitive:true,
    look:'A misty glow split by a dark "lagoon" lane, with a star cluster embedded. Low in the south.',
    facts:'A giant star-forming cloud ~4,000 ly away, big enough to see with the naked eye from a dark site.' },
  { id:'m31', name:'M31 – Andromeda Galaxy', kind:'fixed', ra:0.7123, dec:41.2689, type:'Galaxy', constellation:'Andromeda', mag:3.4, showpiece:5, moonSensitive:true,
    look:'A large oval smudge — the bright core is easiest; needs a dark sky for the full glow.',
    facts:'The most distant thing visible to the naked eye — 2.5 million light-years — and on a collision course with us.' },
];
